create database btl;
use btl;
drop database btl;

CREATE TABLE chi_tiet (
  id_chitiet int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  cid int(11) NOT NULL,
  img text NOT NULL,
  title varchar(1000) NOT NULL,
  code varchar(1000) DEFAULT NULL,
  description varchar(1000) NOT NULL,
  body varchar(10000) NOT NULL,
  price int(11) NOT NULL
);

INSERT INTO chi_tiet ( cid, img, title, code, description, body, price) VALUES
(1, 'slide1.jpg', 'Phòng trọ siêu xinh', NULL, 'Nhà trọ vừa xây năm 2017 . Diện tích ngang 10m dài 20m , dãy trọ có 1 tầng', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</p>', 2010900),
(1, 'slide2.jpg', 'Khu trọ rộng rãi', NULL, 'Ngoài ra Khu trọ nằm lọt thỏm trên tuyến đường chính giữa các Khu công nghiệp nên dân cư vô cùng đông đúc', '<p Ngoài ra Khu trọ nằm lọt thỏm trên tuyến đường chính giữa các Khu công nghiệp nên dân cư vô cùng đông đúc, thường xuyên được các công ty bên KCN đến hỏi thuê cho nhân viên.\r\nVề An Ninh : do nằm gần UBND nên an ninh rất tốt , có bảo vệ dân phố trực thường xuyên . Bên cạnh đó dãy trọ còn được trang bị hệ thống camera giám sát 24/24 và hệ thống theo dỏi ra vào bằng dấu vân tay hiện đại , giúp gia chủ quản lý được từ xa thông qua Smart phone .\r\nPháp lý : nhà trọ được xây trên diện tích đất thổ cư hoàn toàn , có giấy tờ đầy đủ ( sổ hồng ) và không nằm trong khu quy hoạch nào nên không lo bị tranh chấp pháp lý hay bị giải tỏa .</p>', 98600),
(1, 'slide2.jpg', 'Khu trọ mới xây', NULL, 'Bên cạnh đó dãy trọ còn được trang bị hệ thống camera giám sát 24/24 và hệ thống theo dỏi', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</br>\r\nPháp lý : nhà trọ được xây trên diện tích đất thổ cư hoàn toàn , có giấy tờ đầy đủ ( sổ hồng ) và không nằm trong khu quy hoạch nào nên không lo bị tranh chấp pháp lý hay bị giải tỏa .</p>', 2290000),
(1, 'slide3.jpg', 'Phòng trọ (35-40m2) rộng', NULL, 'Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</p>', 9900000),
(1, 'slide4.jpg', 'Vị trí thuận tiện đi lại', NULL, 'Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do</br>\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng</br>\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</p>', 1290000),
(1, 'slide1.jpg', 'Nhà khung BT chắc chắn', NULL, 'Nhà khung BT chắc chắn 4 tầng.\r\n', '<p style=\"text-align: justify;\"Nhà khung BT chắc chắn 4 tầng.\r\n\r\nDTSD DTXD 30m2x4T (120m2), Mặt tiền 3,3m gồm: 01 phòng khách +bếp, 03 phòng ngủ, 03 WC, có đầy đủ phòng thờ, sân phơi. Toàn bộ cửa 100% gỗ Lim dày 3cm, Cửa đi hai lớp, ngoài xếp sắt, trong gỗ lim Pa nô kính. Ban công hàng rào sắt chuồng cọp thép (16×16) A120. Tầng thượng lợp mái tôn Việt Nhật, cột D70, vì kèo thép V50, chân cột đổ Bê tông chắc chắn, Nội thất đầy đủ, chỉ việc dọn đến ở, Không phải chi phí thêm đồng nào?</br>\r\n\r\nVị trí: Gần hồ Triều Khúc, Cách trục đường ô tô tải 30m, Gần nhiều trường Đại học lớn: ĐHCNGT vận tải, ĐH Hà Nội, kiến trúc, nhân văn, Thăng Long, an ninh, HV mật mã, Bưu chính viễn thông\r\n\r\n</p>', 3220000),
(1, 'slide2.jpg', 'Áo Bomber Jacket Dù', NULL, 'Nhà khung BT chắc chắn 4 tầng.\r\n, wifi tốc độ cao', '<p>Cho thuê phòng trọ cao cấp quận bình thạnh Phòng mới xây sạch sẽ, thoáng mát. Khu nhà cao tầng, rất an ninh,có camera giám sát xe 24/24\r\n– Full nội thất : giường, nệm, bàn ghế làm việc, bếp,máy lạnh, tủ lạnh…\r\n– Giờ giấc tự do, không chung chủ\r\nĐiện 4k xe thứ 2 trở đi 200k/1xe còn lại free hết\r\n– Chủ siêu dễ tính, vui vẻ\r\n– Phòng gần trường Hutech, GTVT, Ngoại Thương, Gần Landmark, gần chợ, …\r\nĐịa chỉ:\r\n</p>\r\n\r\n', 3190000),
(1, 'slide3.jpg', 'Nhà quay hướng đông nam', NULL, 'Cho thuê 1 phòng đầy đủ tiện nghi (giường, bàn phấn đẹp, điều hoà, nóng lạnh)', '<p style=\"text-align: justify;\">Cho thuê 1 phòng đầy đủ tiện nghi (giường, bàn phấn đẹp, điều hoà, nóng lạnh) nhà mặt đường Miếu Hai Xã.\r\nPhòng full nội thất, điện nước giá dân.\r\nNấu ăn tầng 1 có bếp rộng rãi.\r\nNhà quay hướng đông nam nên rất mát mẻ, an ninh cực tốt, dân trí cao.\r\nGiá phòng hợp lý\r\nLiên hệ inb hoặc call ngay để xem phòng nhé:\r\nCác mẫu quảng cáo cho thuê phòng trọ trên đây nhận được rất nhiều tương tác từ mọi người. Hy vọng những thông tin trên sẽ hữu ích với tất cả mọi người. Cảm ơn mọi người đã theo dõi bài viết.</p>', 99000),
(1, 'slide4.jpg', 'Phòng mới xây sạch sẽ', NULL, 'Cho thuê phòng trọ cao cấp quận bình thạnh Phòng mới xây sạch sẽ, thoáng mát.', '<p style=\"text-align: justify;\">Cho thuê phòng trọ cao cấp quận bình thạnh Phòng mới xây sạch sẽ, thoáng mát. Khu nhà cao tầng, rất an ninh,có camera giám sát xe 24/24</br>\r\n– Full nội thất : giường, nệm, bàn ghế làm việc, bếp,máy lạnh, tủ lạnh…\r\n– Giờ giấc tự do, không chung chủ</br>\r\nĐiện 4k xe thứ 2 trở đi 200k/1xe còn lại free hết\r\n– Chủ siêu dễ tính, vui vẻ</br>\r\n– Phòng gần trường Hutech, GTVT, Ngoại Thương, Gần Landmark, gần chợ, …\r\nĐịa chỉ:</p>', 3100000),
(1, 'slide1.jpg', 'Giờ giấc tự do', NULL, 'giường, nệm, bàn ghế làm việc, bếp,máy lạnh, tủ lạnh…\r\n– Giờ giấc tự do, không chung chủ', '<p style=\"text-align: justify;\">Cho thuê phòng trọ cao cấp quận bình thạnh Phòng mới xây sạch sẽ, thoáng mát. Khu nhà cao tầng, rất an ninh,có camera giám sát xe 24/24\r\n– Full nội thất : giường, nệm, bàn ghế làm việc, bếp,máy lạnh, tủ lạnh…\r\n– Giờ giấc tự do, không chung chủ\r\nĐiện 4k xe thứ 2 trở đi 200k/1xe còn lại free hết\r\n– Chủ siêu dễ tính, vui vẻ\r\n– Phòng gần trường Hutech, GTVT, Ngoại Thương, Gần Landmark, gần chợ, …\r\nĐịa chỉ:</p>', 1490000),

(2, 'slide2.jpg', ' Nhà trọ an ninh tốt', NULL, 'hòng mới xây,rộng rãi,thoáng mát. Phòng có 2 cửa sổ lấy gió đường luồng thoáng mát', '<p style=\"text-align: justify;\">Phòng trọ cho thuê trong nhà nguyên căn hiện đại .Khu vực Trung Tâm Thành Phố,\r\nQuận Hải Châu,đường Mai Lão Bạng,Đống Đa,,gần trường Cao Đẳng Công Nghệ,\r\nĐại Học Duy Tân (Quang Trung),gần chợ Đống Đa,.Khu dân trí cao,văn minh,an ninh.</br>\r\nPhòng có gác lửng.Phòng mới xây,rộng rãi,thoáng mát. Phòng có 2 cửa sổ lấy gió đường luồng thoáng mát,Chủ nhà thân thiện,vui vẻ ?\r\nKhông chung chủ,giờ giấc thoải mái,WC riêng trong phòng,miễn phí wifi.Chỗ để xe rộng rãi,có camera quan sát.\r\nGía thuê: 2.000.000\r\nLiên hệ chính chủ :</p>', 1780000),
(2, 'slide3.jpg', 'Cho thuê 1 phòng đầy đủ tiện nghi ', NULL, 'Cho thuê 1 phòng đầy đủ tiện nghi ', '<p style=\"text-align: justify;\">Cho thuê 1 phòng đầy đủ tiện nghi (giường, bàn phấn đẹp, điều hoà, nóng lạnh) nhà mặt đường Miếu Hai Xã.\r\nPhòng full nội thất, điện nước giá dân.\r\nNấu ăn tầng 1 có bếp rộng rãi.\r\nNhà quay hướng đông nam nên rất mát mẻ, an ninh cực tốt, dân trí cao.\r\nGiá phòng hợp lý</br>\r\nLiên hệ inb hoặc call ngay để xem phòng nhé:\r\nCác mẫu quảng cáo cho thuê phòng trọ trên đây nhận được rất nhiều tương tác từ mọi người. Hy vọng những thông tin trên sẽ hữu ích với tất cả mọi người. Cảm ơn mọi người đã theo dõi bài viết.</p>', 3200000),
(2, 'slide4.jpg', 'Có khu vực để xe máy riêng', NULL, 'Có gác đúc kiên cố – trần cao 4m , bên hông nhà trọ có thiết kế lối đi riêng và có khu vực để xe máy riêng', '<p style=\"text-align: justify;\">Nhà trọ vừa xây năm 2017 . Diện tích ngang 10m dài 20m , dãy trọ có 1 tầng , mỗi tầng  10 phòng  với diện tích mỗi phòng là 3mx4m, có gác đúc kiên cố – trần cao 4m , bên hông nhà trọ có thiết kế lối đi riêng và có khu vực để xe máy riêng .\r\nPhòng dưới cho thuê 1 triệu 400, phòng  trên cho thuê 1 triệu 300. Tổng thu nhập hàng tháng khoảng  32 triệu ( có thể tăng giá thuê về sau vì phòng còn mới ).</br>\r\nVị trí : nằm gần đường lớn Trần Văn Giàu lộ giới 60m , các tiện ích như : chợ cầu xáng – bệnh viện Tân Tạo , Đại Học Tân Tạo , UBND xã trong bán kính 1km. Từ Nhà trọ di chuyển về bến xe Miền Tây chỉ 15p, cách bệnh viện Nhi đồng Bình Chánh – bệnh viện chợ Rẫy II là 10p,</br>\r\nNgoài ra Khu trọ nằm lọt thỏm trên tuyến đường chính giữa các Khu công nghiệp nên dân cư vô cùng đông đúc, thường xuyên được các công ty bên KCN đến hỏi thuê cho nhân viên.</br>\r\nVề An Ninh : do nằm gần UBND nên an ninh rất tốt , có bảo vệ dân phố trực thường xuyên . Bên cạnh đó dãy trọ còn được trang bị hệ thống camera giám sát 24/24 và hệ thống theo dỏi ra vào bằng dấu vân tay hiện đại , giúp gia chủ quản lý được từ xa thông qua Smart phone .</p>\r\n https://www.facebook.com/chalivnn', 1996000),
(2, 'slide1.jpg', ' Nhà trọ mới xây', NULL, 'Về An Ninh : do nằm gần UBND nên an ninh rất tốt , có bảo vệ dân phố trực thường xuyên', '<p style=\"text-align: justify;\">Về An Ninh : do nằm gần UBND nên an ninh rất tốt , có bảo vệ dân phố trực thường xuyên . </br>Bên cạnh đó dãy trọ còn được trang bị hệ thống camera giám sát 24/24 và hệ thống theo dỏi ra vào bằng dấu vân tay hiện đại , giúp gia chủ quản lý được từ xa thông qua Smart phone .</br>\r\nPháp lý : nhà trọ được xây trên diện tích đất thổ cư hoàn toàn , có giấy tờ đầy đủ ( sổ hồng ) và không nằm trong khu quy hoạch nào nên không lo bị tranh chấp pháp lý hay bị giải tỏa .</br>\r\nGiá bán : 2 tỷ 750 triệu đồng. Khách thanh toán trong vòng 1 tuần sẽ được giảm ngay 30 triệu, bao sang tên và công chứng .\r\nVì bận đi làm nên khách quan tâm vui lòng sắp xếp để xem Nhà vào Chủ nhật là tốt nhất. Liên hệ 090……\r\n\r\nXin cảm ơn đã xem tin.<br/></p>', 149000),
(2, 'slide4.jpg', 'Giờ giấc tự do', NULL, 'giường, nệm, bàn ghế làm việc, bếp,máy lạnh, tủ lạnh…\r\n– Giờ giấc tự do, không chung chủ', '<p style=\"text-align: justify;\">Cho thuê phòng trọ cao cấp quận bình thạnh Phòng mới xây sạch sẽ, thoáng mát. Khu nhà cao tầng, rất an ninh,có camera giám sát xe 24/24\r\n– Full nội thất : giường, nệm, bàn ghế làm việc, bếp,máy lạnh, tủ lạnh…\r\n– Giờ giấc tự do, không chung chủ\r\nĐiện 4k xe thứ 2 trở đi 200k/1xe còn lại free hết\r\n– Chủ siêu dễ tính, vui vẻ\r\n– Phòng gần trường Hutech, GTVT, Ngoại Thương, Gần Landmark, gần chợ, …\r\nĐịa chỉ:</p>', 1490000),
(2, 'slide1.jpg', 'Phòng trọ siêu xinh', NULL, 'Nhà trọ vừa xây năm 2017 . Diện tích ngang 10m dài 20m , dãy trọ có 1 tầng', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</p>', 2010900),
(2, 'slide2.jpg', 'Khu trọ rộng rãi', NULL, 'Ngoài ra Khu trọ nằm lọt thỏm trên tuyến đường chính giữa các Khu công nghiệp nên dân cư vô cùng đông đúc', '<p Ngoài ra Khu trọ nằm lọt thỏm trên tuyến đường chính giữa các Khu công nghiệp nên dân cư vô cùng đông đúc, thường xuyên được các công ty bên KCN đến hỏi thuê cho nhân viên.\r\nVề An Ninh : do nằm gần UBND nên an ninh rất tốt , có bảo vệ dân phố trực thường xuyên . Bên cạnh đó dãy trọ còn được trang bị hệ thống camera giám sát 24/24 và hệ thống theo dỏi ra vào bằng dấu vân tay hiện đại , giúp gia chủ quản lý được từ xa thông qua Smart phone .\r\nPháp lý : nhà trọ được xây trên diện tích đất thổ cư hoàn toàn , có giấy tờ đầy đủ ( sổ hồng ) và không nằm trong khu quy hoạch nào nên không lo bị tranh chấp pháp lý hay bị giải tỏa .</p>', 98600),
(2, 'slide2.jpg', 'Khu trọ mới xây', NULL, 'Bên cạnh đó dãy trọ còn được trang bị hệ thống camera giám sát 24/24 và hệ thống theo dỏi', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</br>\r\nPháp lý : nhà trọ được xây trên diện tích đất thổ cư hoàn toàn , có giấy tờ đầy đủ ( sổ hồng ) và không nằm trong khu quy hoạch nào nên không lo bị tranh chấp pháp lý hay bị giải tỏa .</p>', 2290000),
(2, 'slide3.jpg', 'Phòng trọ (35-40m2) rộng', NULL, 'Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</p>', 9900000),
(2, 'slide4.jpg', 'Vị trí thuận tiện đi lại', NULL, 'Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do</br>\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng</br>\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</p>', 1290000),

(3, 'slide2.jpg', ' Nhà trọ an ninh tốt', NULL, 'hòng mới xây,rộng rãi,thoáng mát. Phòng có 2 cửa sổ lấy gió đường luồng thoáng mát', '<p style=\"text-align: justify;\">Phòng trọ cho thuê trong nhà nguyên căn hiện đại .Khu vực Trung Tâm Thành Phố,\r\nQuận Hải Châu,đường Mai Lão Bạng,Đống Đa,,gần trường Cao Đẳng Công Nghệ,\r\nĐại Học Duy Tân (Quang Trung),gần chợ Đống Đa,.Khu dân trí cao,văn minh,an ninh.</br>\r\nPhòng có gác lửng.Phòng mới xây,rộng rãi,thoáng mát. Phòng có 2 cửa sổ lấy gió đường luồng thoáng mát,Chủ nhà thân thiện,vui vẻ ?\r\nKhông chung chủ,giờ giấc thoải mái,WC riêng trong phòng,miễn phí wifi.Chỗ để xe rộng rãi,có camera quan sát.\r\nGía thuê: 2.000.000\r\nLiên hệ chính chủ :</p>', 1780000),
(3, 'slide3.jpg', 'Cho thuê 1 phòng đầy đủ tiện nghi ', NULL, 'Cho thuê 1 phòng đầy đủ tiện nghi ', '<p style=\"text-align: justify;\">Cho thuê 1 phòng đầy đủ tiện nghi (giường, bàn phấn đẹp, điều hoà, nóng lạnh) nhà mặt đường Miếu Hai Xã.\r\nPhòng full nội thất, điện nước giá dân.\r\nNấu ăn tầng 1 có bếp rộng rãi.\r\nNhà quay hướng đông nam nên rất mát mẻ, an ninh cực tốt, dân trí cao.\r\nGiá phòng hợp lý</br>\r\nLiên hệ inb hoặc call ngay để xem phòng nhé:\r\nCác mẫu quảng cáo cho thuê phòng trọ trên đây nhận được rất nhiều tương tác từ mọi người. Hy vọng những thông tin trên sẽ hữu ích với tất cả mọi người. Cảm ơn mọi người đã theo dõi bài viết.</p>', 3200000),
(3, 'slide4.jpg', 'Có khu vực để xe máy riêng', NULL, 'Có gác đúc kiên cố – trần cao 4m , bên hông nhà trọ có thiết kế lối đi riêng và có khu vực để xe máy riêng', '<p style=\"text-align: justify;\">Nhà trọ vừa xây năm 2017 . Diện tích ngang 10m dài 20m , dãy trọ có 1 tầng , mỗi tầng  10 phòng  với diện tích mỗi phòng là 3mx4m, có gác đúc kiên cố – trần cao 4m , bên hông nhà trọ có thiết kế lối đi riêng và có khu vực để xe máy riêng .\r\nPhòng dưới cho thuê 1 triệu 400, phòng  trên cho thuê 1 triệu 300. Tổng thu nhập hàng tháng khoảng  32 triệu ( có thể tăng giá thuê về sau vì phòng còn mới ).</br>\r\nVị trí : nằm gần đường lớn Trần Văn Giàu lộ giới 60m , các tiện ích như : chợ cầu xáng – bệnh viện Tân Tạo , Đại Học Tân Tạo , UBND xã trong bán kính 1km. Từ Nhà trọ di chuyển về bến xe Miền Tây chỉ 15p, cách bệnh viện Nhi đồng Bình Chánh – bệnh viện chợ Rẫy II là 10p,</br>\r\nNgoài ra Khu trọ nằm lọt thỏm trên tuyến đường chính giữa các Khu công nghiệp nên dân cư vô cùng đông đúc, thường xuyên được các công ty bên KCN đến hỏi thuê cho nhân viên.</br>\r\nVề An Ninh : do nằm gần UBND nên an ninh rất tốt , có bảo vệ dân phố trực thường xuyên . Bên cạnh đó dãy trọ còn được trang bị hệ thống camera giám sát 24/24 và hệ thống theo dỏi ra vào bằng dấu vân tay hiện đại , giúp gia chủ quản lý được từ xa thông qua Smart phone .</p>\r\n https://www.facebook.com/chalivnn', 1996000),
(3, 'slide1.jpg', ' Nhà trọ mới xây', NULL, 'Về An Ninh : do nằm gần UBND nên an ninh rất tốt , có bảo vệ dân phố trực thường xuyên', '<p style=\"text-align: justify;\">Về An Ninh : do nằm gần UBND nên an ninh rất tốt , có bảo vệ dân phố trực thường xuyên . </br>Bên cạnh đó dãy trọ còn được trang bị hệ thống camera giám sát 24/24 và hệ thống theo dỏi ra vào bằng dấu vân tay hiện đại , giúp gia chủ quản lý được từ xa thông qua Smart phone .</br>\r\nPháp lý : nhà trọ được xây trên diện tích đất thổ cư hoàn toàn , có giấy tờ đầy đủ ( sổ hồng ) và không nằm trong khu quy hoạch nào nên không lo bị tranh chấp pháp lý hay bị giải tỏa .</br>\r\nGiá bán : 2 tỷ 750 triệu đồng. Khách thanh toán trong vòng 1 tuần sẽ được giảm ngay 30 triệu, bao sang tên và công chứng .\r\nVì bận đi làm nên khách quan tâm vui lòng sắp xếp để xem Nhà vào Chủ nhật là tốt nhất. Liên hệ 090……\r\n\r\nXin cảm ơn đã xem tin.<br/></p>', 149000),
(3, 'slide4.jpg', 'Giờ giấc tự do', NULL, 'giường, nệm, bàn ghế làm việc, bếp,máy lạnh, tủ lạnh…\r\n– Giờ giấc tự do, không chung chủ', '<p style=\"text-align: justify;\">Cho thuê phòng trọ cao cấp quận bình thạnh Phòng mới xây sạch sẽ, thoáng mát. Khu nhà cao tầng, rất an ninh,có camera giám sát xe 24/24\r\n– Full nội thất : giường, nệm, bàn ghế làm việc, bếp,máy lạnh, tủ lạnh…\r\n– Giờ giấc tự do, không chung chủ\r\nĐiện 4k xe thứ 2 trở đi 200k/1xe còn lại free hết\r\n– Chủ siêu dễ tính, vui vẻ\r\n– Phòng gần trường Hutech, GTVT, Ngoại Thương, Gần Landmark, gần chợ, …\r\nĐịa chỉ:</p>', 1490000),
(3, 'slide1.jpg', 'Phòng trọ siêu xinh', NULL, 'Nhà trọ vừa xây năm 2017 . Diện tích ngang 10m dài 20m , dãy trọ có 1 tầng', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</p>', 2010900),
(3, 'slide2.jpg', 'Khu trọ rộng rãi', NULL, 'Ngoài ra Khu trọ nằm lọt thỏm trên tuyến đường chính giữa các Khu công nghiệp nên dân cư vô cùng đông đúc', '<p Ngoài ra Khu trọ nằm lọt thỏm trên tuyến đường chính giữa các Khu công nghiệp nên dân cư vô cùng đông đúc, thường xuyên được các công ty bên KCN đến hỏi thuê cho nhân viên.\r\nVề An Ninh : do nằm gần UBND nên an ninh rất tốt , có bảo vệ dân phố trực thường xuyên . Bên cạnh đó dãy trọ còn được trang bị hệ thống camera giám sát 24/24 và hệ thống theo dỏi ra vào bằng dấu vân tay hiện đại , giúp gia chủ quản lý được từ xa thông qua Smart phone .\r\nPháp lý : nhà trọ được xây trên diện tích đất thổ cư hoàn toàn , có giấy tờ đầy đủ ( sổ hồng ) và không nằm trong khu quy hoạch nào nên không lo bị tranh chấp pháp lý hay bị giải tỏa .</p>', 98600),
(3, 'slide2.jpg', 'Khu trọ mới xây', NULL, 'Bên cạnh đó dãy trọ còn được trang bị hệ thống camera giám sát 24/24 và hệ thống theo dỏi', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</br>\r\nPháp lý : nhà trọ được xây trên diện tích đất thổ cư hoàn toàn , có giấy tờ đầy đủ ( sổ hồng ) và không nằm trong khu quy hoạch nào nên không lo bị tranh chấp pháp lý hay bị giải tỏa .</p>', 2290000),
(3, 'slide3.jpg', 'Phòng trọ (35-40m2) rộng', NULL, 'Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</p>', 2900000),
(3, 'slide4.jpg', 'Vị trí thuận tiện đi lại', NULL, 'Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do</br>\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng</br>\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</p>', 1290000),

(4, 'slide2.jpg', ' Nhà trọ an ninh tốt', NULL, 'hòng mới xây,rộng rãi,thoáng mát. Phòng có 2 cửa sổ lấy gió đường luồng thoáng mát', '<p style=\"text-align: justify;\">Phòng trọ cho thuê trong nhà nguyên căn hiện đại .Khu vực Trung Tâm Thành Phố,\r\nQuận Hải Châu,đường Mai Lão Bạng,Đống Đa,,gần trường Cao Đẳng Công Nghệ,\r\nĐại Học Duy Tân (Quang Trung),gần chợ Đống Đa,.Khu dân trí cao,văn minh,an ninh.</br>\r\nPhòng có gác lửng.Phòng mới xây,rộng rãi,thoáng mát. Phòng có 2 cửa sổ lấy gió đường luồng thoáng mát,Chủ nhà thân thiện,vui vẻ ?\r\nKhông chung chủ,giờ giấc thoải mái,WC riêng trong phòng,miễn phí wifi.Chỗ để xe rộng rãi,có camera quan sát.\r\nGía thuê: 2.000.000\r\nLiên hệ chính chủ :</p>', 3780000),
(4, 'slide3.jpg', 'Cho thuê 1 phòng đầy đủ tiện nghi ', NULL, 'Cho thuê 1 phòng đầy đủ tiện nghi ', '<p style=\"text-align: justify;\">Cho thuê 1 phòng đầy đủ tiện nghi (giường, bàn phấn đẹp, điều hoà, nóng lạnh) nhà mặt đường Miếu Hai Xã.\r\nPhòng full nội thất, điện nước giá dân.\r\nNấu ăn tầng 1 có bếp rộng rãi.\r\nNhà quay hướng đông nam nên rất mát mẻ, an ninh cực tốt, dân trí cao.\r\nGiá phòng hợp lý</br>\r\nLiên hệ inb hoặc call ngay để xem phòng nhé:\r\nCác mẫu quảng cáo cho thuê phòng trọ trên đây nhận được rất nhiều tương tác từ mọi người. Hy vọng những thông tin trên sẽ hữu ích với tất cả mọi người. Cảm ơn mọi người đã theo dõi bài viết.</p>', 3200000),
(4, 'slide4.jpg', 'Có khu vực để xe máy riêng', NULL, 'Có gác đúc kiên cố – trần cao 4m , bên hông nhà trọ có thiết kế lối đi riêng và có khu vực để xe máy riêng', '<p style=\"text-align: justify;\">Nhà trọ vừa xây năm 2017 . Diện tích ngang 10m dài 20m , dãy trọ có 1 tầng , mỗi tầng  10 phòng  với diện tích mỗi phòng là 3mx4m, có gác đúc kiên cố – trần cao 4m , bên hông nhà trọ có thiết kế lối đi riêng và có khu vực để xe máy riêng .\r\nPhòng dưới cho thuê 1 triệu 400, phòng  trên cho thuê 1 triệu 300. Tổng thu nhập hàng tháng khoảng  32 triệu ( có thể tăng giá thuê về sau vì phòng còn mới ).</br>\r\nVị trí : nằm gần đường lớn Trần Văn Giàu lộ giới 60m , các tiện ích như : chợ cầu xáng – bệnh viện Tân Tạo , Đại Học Tân Tạo , UBND xã trong bán kính 1km. Từ Nhà trọ di chuyển về bến xe Miền Tây chỉ 15p, cách bệnh viện Nhi đồng Bình Chánh – bệnh viện chợ Rẫy II là 10p,</br>\r\nNgoài ra Khu trọ nằm lọt thỏm trên tuyến đường chính giữa các Khu công nghiệp nên dân cư vô cùng đông đúc, thường xuyên được các công ty bên KCN đến hỏi thuê cho nhân viên.</br>\r\nVề An Ninh : do nằm gần UBND nên an ninh rất tốt , có bảo vệ dân phố trực thường xuyên . Bên cạnh đó dãy trọ còn được trang bị hệ thống camera giám sát 24/24 và hệ thống theo dỏi ra vào bằng dấu vân tay hiện đại , giúp gia chủ quản lý được từ xa thông qua Smart phone .</p>\r\n https://www.facebook.com/chalivnn', 4996000),
(4, 'slide1.jpg', ' Nhà trọ mới xây', NULL, 'Về An Ninh : do nằm gần UBND nên an ninh rất tốt , có bảo vệ dân phố trực thường xuyên', '<p style=\"text-align: justify;\">Về An Ninh : do nằm gần UBND nên an ninh rất tốt , có bảo vệ dân phố trực thường xuyên . </br>Bên cạnh đó dãy trọ còn được trang bị hệ thống camera giám sát 24/24 và hệ thống theo dỏi ra vào bằng dấu vân tay hiện đại , giúp gia chủ quản lý được từ xa thông qua Smart phone .</br>\r\nPháp lý : nhà trọ được xây trên diện tích đất thổ cư hoàn toàn , có giấy tờ đầy đủ ( sổ hồng ) và không nằm trong khu quy hoạch nào nên không lo bị tranh chấp pháp lý hay bị giải tỏa .</br>\r\nGiá bán : 2 tỷ 750 triệu đồng. Khách thanh toán trong vòng 1 tuần sẽ được giảm ngay 30 triệu, bao sang tên và công chứng .\r\nVì bận đi làm nên khách quan tâm vui lòng sắp xếp để xem Nhà vào Chủ nhật là tốt nhất. Liên hệ 090……\r\n\r\nXin cảm ơn đã xem tin.<br/></p>', 3149000),
(4, 'slide4.jpg', 'Giờ giấc tự do', NULL, 'giường, nệm, bàn ghế làm việc, bếp,máy lạnh, tủ lạnh…\r\n– Giờ giấc tự do, không chung chủ', '<p style=\"text-align: justify;\">Cho thuê phòng trọ cao cấp quận bình thạnh Phòng mới xây sạch sẽ, thoáng mát. Khu nhà cao tầng, rất an ninh,có camera giám sát xe 24/24\r\n– Full nội thất : giường, nệm, bàn ghế làm việc, bếp,máy lạnh, tủ lạnh…\r\n– Giờ giấc tự do, không chung chủ\r\nĐiện 4k xe thứ 2 trở đi 200k/1xe còn lại free hết\r\n– Chủ siêu dễ tính, vui vẻ\r\n– Phòng gần trường Hutech, GTVT, Ngoại Thương, Gần Landmark, gần chợ, …\r\nĐịa chỉ:</p>', 4490000),
(4, 'slide1.jpg', 'Phòng trọ siêu xinh', NULL, 'Nhà trọ vừa xây năm 2017 . Diện tích ngang 10m dài 20m , dãy trọ có 1 tầng', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</p>', 3010900),
(4, 'slide2.jpg', 'Khu trọ rộng rãi', NULL, 'Ngoài ra Khu trọ nằm lọt thỏm trên tuyến đường chính giữa các Khu công nghiệp nên dân cư vô cùng đông đúc', '<p Ngoài ra Khu trọ nằm lọt thỏm trên tuyến đường chính giữa các Khu công nghiệp nên dân cư vô cùng đông đúc, thường xuyên được các công ty bên KCN đến hỏi thuê cho nhân viên.\r\nVề An Ninh : do nằm gần UBND nên an ninh rất tốt , có bảo vệ dân phố trực thường xuyên . Bên cạnh đó dãy trọ còn được trang bị hệ thống camera giám sát 24/24 và hệ thống theo dỏi ra vào bằng dấu vân tay hiện đại , giúp gia chủ quản lý được từ xa thông qua Smart phone .\r\nPháp lý : nhà trọ được xây trên diện tích đất thổ cư hoàn toàn , có giấy tờ đầy đủ ( sổ hồng ) và không nằm trong khu quy hoạch nào nên không lo bị tranh chấp pháp lý hay bị giải tỏa .</p>', 4398600),
(4, 'slide2.jpg', 'Khu trọ mới xây', NULL, 'Bên cạnh đó dãy trọ còn được trang bị hệ thống camera giám sát 24/24 và hệ thống theo dỏi', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</br>\r\nPháp lý : nhà trọ được xây trên diện tích đất thổ cư hoàn toàn , có giấy tờ đầy đủ ( sổ hồng ) và không nằm trong khu quy hoạch nào nên không lo bị tranh chấp pháp lý hay bị giải tỏa .</p>', 4290000),
(4, 'slide3.jpg', 'Phòng trọ (35-40m2) rộng', NULL, 'Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</p>', 4900000),
(4, 'slide4.jpg', 'Vị trí thuận tiện đi lại', NULL, 'Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do</br>\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng</br>\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</p>', 3290000),

(5, 'slide2.jpg', ' Nhà trọ an ninh tốt', NULL, 'hòng mới xây,rộng rãi,thoáng mát. Phòng có 2 cửa sổ lấy gió đường luồng thoáng mát', '<p style=\"text-align: justify;\">Phòng trọ cho thuê trong nhà nguyên căn hiện đại .Khu vực Trung Tâm Thành Phố,\r\nQuận Hải Châu,đường Mai Lão Bạng,Đống Đa,,gần trường Cao Đẳng Công Nghệ,\r\nĐại Học Duy Tân (Quang Trung),gần chợ Đống Đa,.Khu dân trí cao,văn minh,an ninh.</br>\r\nPhòng có gác lửng.Phòng mới xây,rộng rãi,thoáng mát. Phòng có 2 cửa sổ lấy gió đường luồng thoáng mát,Chủ nhà thân thiện,vui vẻ ?\r\nKhông chung chủ,giờ giấc thoải mái,WC riêng trong phòng,miễn phí wifi.Chỗ để xe rộng rãi,có camera quan sát.\r\nGía thuê: 2.000.000\r\nLiên hệ chính chủ :</p>', 5780000),
(5, 'slide3.jpg', 'Cho thuê 1 phòng đầy đủ tiện nghi ', NULL, 'Cho thuê 1 phòng đầy đủ tiện nghi ', '<p style=\"text-align: justify;\">Cho thuê 1 phòng đầy đủ tiện nghi (giường, bàn phấn đẹp, điều hoà, nóng lạnh) nhà mặt đường Miếu Hai Xã.\r\nPhòng full nội thất, điện nước giá dân.\r\nNấu ăn tầng 1 có bếp rộng rãi.\r\nNhà quay hướng đông nam nên rất mát mẻ, an ninh cực tốt, dân trí cao.\r\nGiá phòng hợp lý</br>\r\nLiên hệ inb hoặc call ngay để xem phòng nhé:\r\nCác mẫu quảng cáo cho thuê phòng trọ trên đây nhận được rất nhiều tương tác từ mọi người. Hy vọng những thông tin trên sẽ hữu ích với tất cả mọi người. Cảm ơn mọi người đã theo dõi bài viết.</p>', 7200000),
(5, 'slide4.jpg', 'Có khu vực để xe máy riêng', NULL, 'Có gác đúc kiên cố – trần cao 4m , bên hông nhà trọ có thiết kế lối đi riêng và có khu vực để xe máy riêng', '<p style=\"text-align: justify;\">Nhà trọ vừa xây năm 2017 . Diện tích ngang 10m dài 20m , dãy trọ có 1 tầng , mỗi tầng  10 phòng  với diện tích mỗi phòng là 3mx4m, có gác đúc kiên cố – trần cao 4m , bên hông nhà trọ có thiết kế lối đi riêng và có khu vực để xe máy riêng .\r\nPhòng dưới cho thuê 1 triệu 400, phòng  trên cho thuê 1 triệu 300. Tổng thu nhập hàng tháng khoảng  32 triệu ( có thể tăng giá thuê về sau vì phòng còn mới ).</br>\r\nVị trí : nằm gần đường lớn Trần Văn Giàu lộ giới 60m , các tiện ích như : chợ cầu xáng – bệnh viện Tân Tạo , Đại Học Tân Tạo , UBND xã trong bán kính 1km. Từ Nhà trọ di chuyển về bến xe Miền Tây chỉ 15p, cách bệnh viện Nhi đồng Bình Chánh – bệnh viện chợ Rẫy II là 10p,</br>\r\nNgoài ra Khu trọ nằm lọt thỏm trên tuyến đường chính giữa các Khu công nghiệp nên dân cư vô cùng đông đúc, thường xuyên được các công ty bên KCN đến hỏi thuê cho nhân viên.</br>\r\nVề An Ninh : do nằm gần UBND nên an ninh rất tốt , có bảo vệ dân phố trực thường xuyên . Bên cạnh đó dãy trọ còn được trang bị hệ thống camera giám sát 24/24 và hệ thống theo dỏi ra vào bằng dấu vân tay hiện đại , giúp gia chủ quản lý được từ xa thông qua Smart phone .</p>\r\n https://www.facebook.com/chalivnn', 7996000),
(5, 'slide1.jpg', ' Nhà trọ mới xây', NULL, 'Về An Ninh : do nằm gần UBND nên an ninh rất tốt , có bảo vệ dân phố trực thường xuyên', '<p style=\"text-align: justify;\">Về An Ninh : do nằm gần UBND nên an ninh rất tốt , có bảo vệ dân phố trực thường xuyên . </br>Bên cạnh đó dãy trọ còn được trang bị hệ thống camera giám sát 24/24 và hệ thống theo dỏi ra vào bằng dấu vân tay hiện đại , giúp gia chủ quản lý được từ xa thông qua Smart phone .</br>\r\nPháp lý : nhà trọ được xây trên diện tích đất thổ cư hoàn toàn , có giấy tờ đầy đủ ( sổ hồng ) và không nằm trong khu quy hoạch nào nên không lo bị tranh chấp pháp lý hay bị giải tỏa .</br>\r\nGiá bán : 2 tỷ 750 triệu đồng. Khách thanh toán trong vòng 1 tuần sẽ được giảm ngay 30 triệu, bao sang tên và công chứng .\r\nVì bận đi làm nên khách quan tâm vui lòng sắp xếp để xem Nhà vào Chủ nhật là tốt nhất. Liên hệ 090……\r\n\r\nXin cảm ơn đã xem tin.<br/></p>', 8149000),
(5, 'slide4.jpg', 'Giờ giấc tự do', NULL, 'giường, nệm, bàn ghế làm việc, bếp,máy lạnh, tủ lạnh…\r\n– Giờ giấc tự do, không chung chủ', '<p style=\"text-align: justify;\">Cho thuê phòng trọ cao cấp quận bình thạnh Phòng mới xây sạch sẽ, thoáng mát. Khu nhà cao tầng, rất an ninh,có camera giám sát xe 24/24\r\n– Full nội thất : giường, nệm, bàn ghế làm việc, bếp,máy lạnh, tủ lạnh…\r\n– Giờ giấc tự do, không chung chủ\r\nĐiện 4k xe thứ 2 trở đi 200k/1xe còn lại free hết\r\n– Chủ siêu dễ tính, vui vẻ\r\n– Phòng gần trường Hutech, GTVT, Ngoại Thương, Gần Landmark, gần chợ, …\r\nĐịa chỉ:</p>', 1490000),
(5, 'slide1.jpg', 'Phòng trọ siêu xinh', NULL, 'Nhà trọ vừa xây năm 2017 . Diện tích ngang 10m dài 20m , dãy trọ có 1 tầng', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</p>', 6010900),
(5, 'slide2.jpg', 'Khu trọ rộng rãi', NULL, 'Ngoài ra Khu trọ nằm lọt thỏm trên tuyến đường chính giữa các Khu công nghiệp nên dân cư vô cùng đông đúc', '<p Ngoài ra Khu trọ nằm lọt thỏm trên tuyến đường chính giữa các Khu công nghiệp nên dân cư vô cùng đông đúc, thường xuyên được các công ty bên KCN đến hỏi thuê cho nhân viên.\r\nVề An Ninh : do nằm gần UBND nên an ninh rất tốt , có bảo vệ dân phố trực thường xuyên . Bên cạnh đó dãy trọ còn được trang bị hệ thống camera giám sát 24/24 và hệ thống theo dỏi ra vào bằng dấu vân tay hiện đại , giúp gia chủ quản lý được từ xa thông qua Smart phone .\r\nPháp lý : nhà trọ được xây trên diện tích đất thổ cư hoàn toàn , có giấy tờ đầy đủ ( sổ hồng ) và không nằm trong khu quy hoạch nào nên không lo bị tranh chấp pháp lý hay bị giải tỏa .</p>', 9998600),
(5, 'slide2.jpg', 'Khu trọ mới xây', NULL, 'Bên cạnh đó dãy trọ còn được trang bị hệ thống camera giám sát 24/24 và hệ thống theo dỏi', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</br>\r\nPháp lý : nhà trọ được xây trên diện tích đất thổ cư hoàn toàn , có giấy tờ đầy đủ ( sổ hồng ) và không nằm trong khu quy hoạch nào nên không lo bị tranh chấp pháp lý hay bị giải tỏa .</p>', 6290000),
(5, 'slide3.jpg', 'Phòng trọ (35-40m2) rộng', NULL, 'Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</p>', 9900000),
(5, 'slide4.jpg', 'Vị trí thuận tiện đi lại', NULL, 'Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt', '<p style=\"text-align: justify;\">Hiện tại bên mình cho thuê phòng trọ mới xây ngay\r\n– Phòng trọ (35-40m2) rộng rai. Thoát mát ở được 4,5 người\r\n– Ban công, chỗ phơi đồ riêng biệt, wifi tốc độ cao, hệ thống cửa vân tay riêng biệt\r\n– Vị trí thuận tiện đi lỊ các quận trung tâm. Nguyễn Văn Quá, Cầu tham lương Trường Chinh , Quang Trung Gò Vấp , Chợ Hạnh Thông Tây, Công Viên Phần mềm, ngay chợ Cầu. Gần các trường đại học Hoa Sen,FPT.. (PHÙ HỢP CHO CÁC ANH CHỊ LÀM VĂN PHÒNG, SINH VIÊN VÀ HỘ GIA ĐÌNH)\r\n– Phòng mới đẹp có nội thất\r\n– Có giường và gác cao\r\n-Không giới hạn người ở\r\n– Hầm xe rộng thoải mái\r\n– Khu vực an ninh, trật tự, bảo vệ 24/7 yên tỉnh , không chung chủ , giờ giấc tự do</br>\r\nĐẶC BIỆT: giảm giá phí dịch vụ cho hợp đồng 12 tháng</br>\r\n– Cam kết không tăng giá lại trong suốt thời gian gia hợp đồng , ưu tiên khách hàng lịch sự, văn mình , hợp đồng lâu dài</p>', 5290000);

--------------------------------------------------------

CREATE TABLE theloai (
  id_theloai int(11) NOT NULL primary key AUTO_INCREMENT,
  name varchar(30) NOT NULL
);


INSERT INTO theloai (name) VALUES
('Hà Nội'),
('Hồ Chí Minh'),
('1- 3 triệu'),
('3- 5 triệu'),
('5- 10 triệu');

SELECT * FROM theloai LIMIT 1 OFFSET  0;
-- --------------------------------------------------------
drop table users;
CREATE TABLE users (
  id_user int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  username varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  email varchar(255) NOT NULL UNIQUE KEY,
  level int(11) DEFAULT '1'
)

select * from users;
INSERT INTO users ( username, password, email) VALUES
('nhatro', '123', 'nhatro@gmail.com');

INSERT INTO users ( username, password, email, level) VALUES
('admin', '123', 'admin@gmail.com', 0);

-- --------------------------------------------------------

CREATE TABLE login (
  id_user_login int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  email varchar(255) NOT NULL UNIQUE KEY,
  password varchar(255) NOT NULL
)
SELECT * FROM login;
truncate table login;
delete from login;

drop table hop_dong;
CREATE TABLE hop_dong (
  id_hopdong int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  fullname varchar(1000) NOT NULL,
  cmt int(12) NOT NULL,
  sdt int(12) NOT NULL,
  mattruoc text NOT NULL,
  matsau text NOT NULL,
  id_chitiet int(11) NOT NULL,
  CONSTRAINT fk_HopDong_ChiTiet foreign key (id_chitiet) REFERENCES  chi_tiet(id_chitiet),
  id_user int(11) NOT NULL,
  CONSTRAINT fk_HopDong_User foreign key (id_user) REFERENCES users(id_user)
)









